version: '3.4'

services:
  storage:
    container_name: minibank_storage
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: MiniBankDemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19992806ru
    volumes:
      - ~/volumes/postgres:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d MiniBankDemo -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
  app:
    container_name: app
    build:
      context: ..
      dockerfile: build/MiniBank.Dockerfile
    depends_on:
      storage:
        condition: service_healthy
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://localhost:5001;http://localhost:5000
      - "DataBase:ConnectionString=Host=storage;Port=5432;Database=MiniBankDemo;Username=postgres;Password=19992806ru"
